version: '3.3'
services:
  pg:
    container_name: ds_hell_pg
    image: postgres:16.4
#    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432