spring:
  application:
    name: ds-hell-demo-app
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: docker

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    show-sql: true
  flyway:
    enabled: true
    schemas: app_schemas